INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Tulipan', '1P', '1Q', 2, 'Standard');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Tavirozsa', '2P', '2K', 4, 'Suite');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Levendula', '3P', '2S', 2, 'Standard');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Barack', '2A', '1Q', 2, 'Standard');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Jazmin', '3A', '1Q2S', 4, 'Suite');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Oregano', '3D', '1Q', 2, 'Suite');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, CAPACITY, TYPE) VALUES ('Ananasz', '3O', '1Q1S', 4, 'Suite');

-- Q=queen bed, K=king size bed, S=double bed