CREATE TABLE ROOM (
    ROOM_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ROOM_NUMBER VARCHAR(5) NOT NULL UNIQUE,
    BED_INFO VARCHAR(5) NOT NULL,
    CAPACITY INTEGER NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);